# Generated by Django 4.2.7 on 2023-11-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Capacity', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Total', models.IntegerField()),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('IdCabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.cabaña')),
                ('IdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Valor', models.IntegerField()),
                ('IdReservaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.reservaventa')),
                ('IdServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.cabaña')),
                ('IdReservaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.reservaventa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Valor', models.IntegerField()),
                ('IdReservaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.reservaventa')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntuacion', models.IntegerField()),
                ('IdReservaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.reservaventa')),
            ],
        ),
        migrations.CreateModel(
            name='Cabaña_comodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('IdCabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.cabaña')),
                ('IdComodidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.comodidad')),
            ],
        ),
        migrations.AddField(
            model_name='cabaña',
            name='IdTipoCabaña',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.tipocabaña'),
        ),
    ]
